/**
 * @file network.c
 *
 * @brief This source file was generated by cantools version 41.4.3 Sun Aug  2 01:27:04 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "network.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int network_pedal_pack(
    uint8_t *dst_p,
    const struct network_pedal_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->throttle_raw, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->throttle_raw, 8u, 0x7fu);
    dst_p[1] |= pack_left_shift_u8(src_p->kill_flag, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->deadman_active, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->adc_fault, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_active, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->is_calibrating, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->seq_counter, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->raw_throttle_adc, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->raw_throttle_adc, 8u, 0xffu);

    return (6);
}

int network_pedal_unpack(
    struct network_pedal_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->throttle_raw = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->throttle_raw |= unpack_left_shift_u16(src_p[1], 8u, 0x7fu);
    dst_p->kill_flag = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->deadman_active = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->adc_fault = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->brake_active = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->is_calibrating = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->seq_counter = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->raw_throttle_adc = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->raw_throttle_adc |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int network_pedal_init(struct network_pedal_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_pedal_t));

    return 0;
}

uint16_t network_pedal_throttle_raw_encode(double value)
{
    return (uint16_t)(value);
}

double network_pedal_throttle_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool network_pedal_throttle_raw_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool network_pedal_throttle_raw_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 32767.0));
}

uint8_t network_pedal_kill_flag_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_kill_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_kill_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_kill_flag_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_deadman_active_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_deadman_active_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_deadman_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_deadman_active_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_adc_fault_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_adc_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_adc_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_adc_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_brake_active_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_brake_active_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_brake_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_brake_active_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_is_calibrating_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_is_calibrating_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_is_calibrating_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_is_calibrating_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_seq_counter_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_seq_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_seq_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool network_pedal_seq_counter_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint16_t network_pedal_raw_throttle_adc_encode(double value)
{
    return (uint16_t)(value);
}

double network_pedal_raw_throttle_adc_decode(uint16_t value)
{
    return ((double)value);
}

bool network_pedal_raw_throttle_adc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_pedal_raw_throttle_adc_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

int network_aux_ctrl_pack(
    uint8_t *dst_p,
    const struct network_aux_ctrl_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->left_turn, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->right_turn, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->brake_light, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->headlights, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->hazards, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->horn, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->wipers, 6u, 0x40u);

    return (1);
}

int network_aux_ctrl_unpack(
    struct network_aux_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->left_turn = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->right_turn = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->brake_light = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->headlights = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->hazards = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->horn = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->wipers = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int network_aux_ctrl_init(struct network_aux_ctrl_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_aux_ctrl_t));

    return 0;
}

uint8_t network_aux_ctrl_left_turn_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_ctrl_left_turn_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_ctrl_left_turn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_ctrl_left_turn_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_ctrl_right_turn_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_ctrl_right_turn_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_ctrl_right_turn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_ctrl_right_turn_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_ctrl_brake_light_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_ctrl_brake_light_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_ctrl_brake_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_ctrl_brake_light_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_ctrl_headlights_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_ctrl_headlights_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_ctrl_headlights_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_ctrl_headlights_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_ctrl_hazards_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_ctrl_hazards_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_ctrl_hazards_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_ctrl_hazards_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_ctrl_horn_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_ctrl_horn_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_ctrl_horn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_ctrl_horn_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_ctrl_wipers_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_ctrl_wipers_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_ctrl_wipers_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_ctrl_wipers_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int network_pwr_monitor_780_pack(
    uint8_t *dst_p,
    const struct network_pwr_monitor_780_t *src_p,
    size_t size)
{
    uint16_t amps;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->volts, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->volts, 8u, 0xffu);
    amps = (uint16_t)src_p->amps;
    dst_p[2] |= pack_left_shift_u16(amps, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amps, 8u, 0xffu);

    return (4);
}

int network_pwr_monitor_780_unpack(
    struct network_pwr_monitor_780_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amps;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->volts = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->volts |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    amps = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amps |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amps = (int16_t)amps;

    return (0);
}

int network_pwr_monitor_780_init(struct network_pwr_monitor_780_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_pwr_monitor_780_t));

    return 0;
}

uint16_t network_pwr_monitor_780_volts_encode(double value)
{
    return (uint16_t)(value / 0.003125);
}

double network_pwr_monitor_780_volts_decode(uint16_t value)
{
    return ((double)value * 0.003125);
}

bool network_pwr_monitor_780_volts_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_pwr_monitor_780_volts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 204.8));
}

int16_t network_pwr_monitor_780_amps_encode(double value)
{
    return (int16_t)(value / 0.0024);
}

double network_pwr_monitor_780_amps_decode(int16_t value)
{
    return ((double)value * 0.0024);
}

bool network_pwr_monitor_780_amps_is_in_range(int16_t value)
{
    return (value >= -32767);
}

bool network_pwr_monitor_780_amps_is_in_phys_range(double value)
{
    return ((value >= -78.64) && (value <= 78.64));
}

int network_pwr_monitor_740_pack(
    uint8_t *dst_p,
    const struct network_pwr_monitor_740_t *src_p,
    size_t size)
{
    uint16_t amps;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->volts, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->volts, 8u, 0xffu);
    amps = (uint16_t)src_p->amps;
    dst_p[2] |= pack_left_shift_u16(amps, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(amps, 8u, 0xffu);

    return (4);
}

int network_pwr_monitor_740_unpack(
    struct network_pwr_monitor_740_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t amps;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->volts = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->volts |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    amps = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    amps |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->amps = (int16_t)amps;

    return (0);
}

int network_pwr_monitor_740_init(struct network_pwr_monitor_740_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_pwr_monitor_740_t));

    return 0;
}

uint16_t network_pwr_monitor_740_volts_encode(double value)
{
    return (uint16_t)(value / 0.003125);
}

double network_pwr_monitor_740_volts_decode(uint16_t value)
{
    return ((double)value * 0.003125);
}

bool network_pwr_monitor_740_volts_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_pwr_monitor_740_volts_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 204.8));
}

int16_t network_pwr_monitor_740_amps_encode(double value)
{
    return (int16_t)(value / 0.0012);
}

double network_pwr_monitor_740_amps_decode(int16_t value)
{
    return ((double)value * 0.0012);
}

bool network_pwr_monitor_740_amps_is_in_range(int16_t value)
{
    return (value >= -32767);
}

bool network_pwr_monitor_740_amps_is_in_phys_range(double value)
{
    return ((value >= -39.32) && (value <= 39.32));
}

int network_pwr_energy_pack(
    uint8_t *dst_p,
    const struct network_pwr_energy_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u64(src_p->energy_joules, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->energy_joules, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->energy_joules, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->energy_joules, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->energy_joules, 32u, 0xffu);

    return (5);
}

int network_pwr_energy_unpack(
    struct network_pwr_energy_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->energy_joules = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->energy_joules |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->energy_joules |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->energy_joules |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->energy_joules |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);

    return (0);
}

int network_pwr_energy_init(struct network_pwr_energy_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_pwr_energy_t));

    return 0;
}

uint64_t network_pwr_energy_energy_joules_encode(double value)
{
    return (uint64_t)(value / 0.00768);
}

double network_pwr_energy_energy_joules_decode(uint64_t value)
{
    return ((double)value * 0.00768);
}

bool network_pwr_energy_energy_joules_is_in_range(uint64_t value)
{
    return (value <= 1099836467839ull);
}

bool network_pwr_energy_energy_joules_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 8446744073.0));
}

int network_dash_stat_pack(
    uint8_t *dst_p,
    const struct network_dash_stat_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->data, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->data, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->data, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->data, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->data, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->data, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->data, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->data, 56u, 0xffu);

    return (8);
}

int network_dash_stat_unpack(
    struct network_dash_stat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->data = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    dst_p->data |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);

    return (0);
}

int network_dash_stat_init(struct network_dash_stat_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_dash_stat_t));

    return 0;
}

uint64_t network_dash_stat_data_encode(double value)
{
    return (uint64_t)(value);
}

double network_dash_stat_data_decode(uint64_t value)
{
    return ((double)value);
}

bool network_dash_stat_data_is_in_range(uint64_t value)
{
    return (value <= 18446744070000001024ull);
}

bool network_dash_stat_data_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.844674407e+19));
}
