/**
 * @file network.c
 *
 * @brief This source file was generated by cantools version 41.4.3 Sun Sep 13 00:02:49 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "network.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int network_pedal_status_pack(
    uint8_t *dst_p,
    const struct network_pedal_status_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->throttle_command, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->throttle_command, 8u, 0x7fu);
    dst_p[1] |= pack_left_shift_u8(src_p->throttle_inhibit, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->deadman_active, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->adc_fault, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->brake_active, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->is_calibrating, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->inhibit_reason, 4u, 0xf0u);
    dst_p[3] |= pack_left_shift_u8(src_p->seq_counter, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->throttle_adc_raw, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->throttle_adc_raw, 8u, 0xffu);

    return (6);
}

int network_pedal_status_unpack(
    struct network_pedal_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->throttle_command = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->throttle_command |= unpack_left_shift_u16(src_p[1], 8u, 0x7fu);
    dst_p->throttle_inhibit = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->deadman_active = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->adc_fault = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->brake_active = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->is_calibrating = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->inhibit_reason = unpack_right_shift_u8(src_p[2], 4u, 0xf0u);
    dst_p->seq_counter = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->throttle_adc_raw = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->throttle_adc_raw |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int network_pedal_status_init(struct network_pedal_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_pedal_status_t));

    return 0;
}

uint16_t network_pedal_status_throttle_command_encode(double value)
{
    return (uint16_t)(value);
}

double network_pedal_status_throttle_command_decode(uint16_t value)
{
    return ((double)value);
}

bool network_pedal_status_throttle_command_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

bool network_pedal_status_throttle_command_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 32767.0));
}

uint8_t network_pedal_status_throttle_inhibit_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_status_throttle_inhibit_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_status_throttle_inhibit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_status_throttle_inhibit_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_status_deadman_active_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_status_deadman_active_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_status_deadman_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_status_deadman_active_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_status_adc_fault_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_status_adc_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_status_adc_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_status_adc_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_status_brake_active_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_status_brake_active_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_status_brake_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_status_brake_active_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_status_is_calibrating_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_status_is_calibrating_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_status_is_calibrating_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_pedal_status_is_calibrating_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_pedal_status_inhibit_reason_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_status_inhibit_reason_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_status_inhibit_reason_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool network_pedal_status_inhibit_reason_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t network_pedal_status_seq_counter_encode(double value)
{
    return (uint8_t)(value);
}

double network_pedal_status_seq_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool network_pedal_status_seq_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool network_pedal_status_seq_counter_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint16_t network_pedal_status_throttle_adc_raw_encode(double value)
{
    return (uint16_t)(value);
}

double network_pedal_status_throttle_adc_raw_decode(uint16_t value)
{
    return ((double)value);
}

bool network_pedal_status_throttle_adc_raw_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_pedal_status_throttle_adc_raw_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

int network_aux_command_pack(
    uint8_t *dst_p,
    const struct network_aux_command_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->left_turn, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->right_turn, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->headlights, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->hazards, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->horn, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->wipers, 6u, 0x40u);

    return (1);
}

int network_aux_command_unpack(
    struct network_aux_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->left_turn = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->right_turn = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->headlights = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->hazards = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->horn = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->wipers = unpack_right_shift_u8(src_p[0], 6u, 0x40u);

    return (0);
}

int network_aux_command_init(struct network_aux_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_aux_command_t));

    return 0;
}

uint8_t network_aux_command_left_turn_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_command_left_turn_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_command_left_turn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_command_left_turn_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_command_right_turn_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_command_right_turn_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_command_right_turn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_command_right_turn_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_command_headlights_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_command_headlights_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_command_headlights_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_command_headlights_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_command_hazards_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_command_hazards_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_command_hazards_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_command_hazards_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_command_horn_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_command_horn_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_command_horn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_command_horn_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_aux_command_wipers_encode(double value)
{
    return (uint8_t)(value);
}

double network_aux_command_wipers_decode(uint8_t value)
{
    return ((double)value);
}

bool network_aux_command_wipers_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_aux_command_wipers_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int network_pack_power_pack(
    uint8_t *dst_p,
    const struct network_pack_power_t *src_p,
    size_t size)
{
    uint16_t current_a;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage_v, 8u, 0xffu);
    current_a = (uint16_t)src_p->current_a;
    dst_p[2] |= pack_left_shift_u16(current_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_a, 8u, 0xffu);

    return (4);
}

int network_pack_power_unpack(
    struct network_pack_power_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_a;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->voltage_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    current_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_a = (int16_t)current_a;

    return (0);
}

int network_pack_power_init(struct network_pack_power_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_pack_power_t));

    return 0;
}

uint16_t network_pack_power_voltage_v_encode(double value)
{
    return (uint16_t)(value / 0.003125);
}

double network_pack_power_voltage_v_decode(uint16_t value)
{
    return ((double)value * 0.003125);
}

bool network_pack_power_voltage_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_pack_power_voltage_v_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 204.796875));
}

int16_t network_pack_power_current_a_encode(double value)
{
    return (int16_t)(value / 0.0024);
}

double network_pack_power_current_a_decode(int16_t value)
{
    return ((double)value * 0.0024);
}

bool network_pack_power_current_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_pack_power_current_a_is_in_phys_range(double value)
{
    return ((value >= -78.6432) && (value <= 78.6408));
}

int network_aux_power_pack(
    uint8_t *dst_p,
    const struct network_aux_power_t *src_p,
    size_t size)
{
    uint16_t current_a;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->voltage_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->voltage_v, 8u, 0xffu);
    current_a = (uint16_t)src_p->current_a;
    dst_p[2] |= pack_left_shift_u16(current_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_a, 8u, 0xffu);

    return (4);
}

int network_aux_power_unpack(
    struct network_aux_power_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_a;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->voltage_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->voltage_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    current_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_a = (int16_t)current_a;

    return (0);
}

int network_aux_power_init(struct network_aux_power_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_aux_power_t));

    return 0;
}

uint16_t network_aux_power_voltage_v_encode(double value)
{
    return (uint16_t)(value / 0.003125);
}

double network_aux_power_voltage_v_decode(uint16_t value)
{
    return ((double)value * 0.003125);
}

bool network_aux_power_voltage_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_aux_power_voltage_v_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 204.796875));
}

int16_t network_aux_power_current_a_encode(double value)
{
    return (int16_t)(value / 0.0012);
}

double network_aux_power_current_a_decode(int16_t value)
{
    return ((double)value * 0.0012);
}

bool network_aux_power_current_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_aux_power_current_a_is_in_phys_range(double value)
{
    return ((value >= -39.3216) && (value <= 39.3204));
}

int network_pack_energy_pack(
    uint8_t *dst_p,
    const struct network_pack_energy_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u64(src_p->energy_j, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->energy_j, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->energy_j, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->energy_j, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->energy_j, 32u, 0xffu);

    return (5);
}

int network_pack_energy_unpack(
    struct network_pack_energy_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->energy_j = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->energy_j |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->energy_j |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->energy_j |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->energy_j |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);

    return (0);
}

int network_pack_energy_init(struct network_pack_energy_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_pack_energy_t));

    return 0;
}

uint64_t network_pack_energy_energy_j_encode(double value)
{
    return (uint64_t)(value / 0.00768);
}

double network_pack_energy_energy_j_decode(uint64_t value)
{
    return ((double)value * 0.00768);
}

bool network_pack_energy_energy_j_is_in_range(uint64_t value)
{
    return (value <= 1099511627775ull);
}

bool network_pack_energy_energy_j_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 8444249301.312));
}

int network_vehicle_motion_pack(
    uint8_t *dst_p,
    const struct network_vehicle_motion_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->speed_kmh, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->speed_kmh, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u32(src_p->trip_distance_m, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->trip_distance_m, 8u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->trip_distance_m, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->trip_distance_m, 24u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->motion_valid, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->seq_counter, 0u, 0xffu);

    return (8);
}

int network_vehicle_motion_unpack(
    struct network_vehicle_motion_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->speed_kmh = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->speed_kmh |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->trip_distance_m = unpack_right_shift_u32(src_p[2], 0u, 0xffu);
    dst_p->trip_distance_m |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
    dst_p->trip_distance_m |= unpack_left_shift_u32(src_p[4], 16u, 0xffu);
    dst_p->trip_distance_m |= unpack_left_shift_u32(src_p[5], 24u, 0xffu);
    dst_p->motion_valid = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->seq_counter = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int network_vehicle_motion_init(struct network_vehicle_motion_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_vehicle_motion_t));

    return 0;
}

uint16_t network_vehicle_motion_speed_kmh_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double network_vehicle_motion_speed_kmh_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool network_vehicle_motion_speed_kmh_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_vehicle_motion_speed_kmh_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 655.35));
}

uint32_t network_vehicle_motion_trip_distance_m_encode(double value)
{
    return (uint32_t)(value / 0.1);
}

double network_vehicle_motion_trip_distance_m_decode(uint32_t value)
{
    return ((double)value * 0.1);
}

bool network_vehicle_motion_trip_distance_m_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool network_vehicle_motion_trip_distance_m_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 429496729.5));
}

uint8_t network_vehicle_motion_motion_valid_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_motion_motion_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_motion_motion_valid_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_vehicle_motion_motion_valid_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_vehicle_motion_seq_counter_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_motion_seq_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_motion_seq_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool network_vehicle_motion_seq_counter_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int network_vehicle_time_pack(
    uint8_t *dst_p,
    const struct network_vehicle_time_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->year, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->month, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->day, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->hour, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->minute, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->second, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->gps_synced, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->rtc_valid, 1u, 0x02u);

    return (7);
}

int network_vehicle_time_unpack(
    struct network_vehicle_time_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->year = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->month = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->day = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->hour = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->minute = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->second = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->gps_synced = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->rtc_valid = unpack_right_shift_u8(src_p[6], 1u, 0x02u);

    return (0);
}

int network_vehicle_time_init(struct network_vehicle_time_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_vehicle_time_t));

    return 0;
}

uint8_t network_vehicle_time_year_encode(double value)
{
    return (uint8_t)(value - 2000.0);
}

double network_vehicle_time_year_decode(uint8_t value)
{
    return ((double)value + 2000.0);
}

bool network_vehicle_time_year_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool network_vehicle_time_year_is_in_phys_range(double value)
{
    return ((value >= 2000.0) && (value <= 2255.0));
}

uint8_t network_vehicle_time_month_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_time_month_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_time_month_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 12u));
}

bool network_vehicle_time_month_is_in_phys_range(double value)
{
    return ((value >= 1.0) && (value <= 12.0));
}

uint8_t network_vehicle_time_day_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_time_day_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_time_day_is_in_range(uint8_t value)
{
    return ((value >= 1u) && (value <= 31u));
}

bool network_vehicle_time_day_is_in_phys_range(double value)
{
    return ((value >= 1.0) && (value <= 31.0));
}

uint8_t network_vehicle_time_hour_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_time_hour_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_time_hour_is_in_range(uint8_t value)
{
    return (value <= 23u);
}

bool network_vehicle_time_hour_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 23.0));
}

uint8_t network_vehicle_time_minute_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_time_minute_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_time_minute_is_in_range(uint8_t value)
{
    return (value <= 59u);
}

bool network_vehicle_time_minute_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 59.0));
}

uint8_t network_vehicle_time_second_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_time_second_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_time_second_is_in_range(uint8_t value)
{
    return (value <= 59u);
}

bool network_vehicle_time_second_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 59.0));
}

uint8_t network_vehicle_time_gps_synced_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_time_gps_synced_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_time_gps_synced_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_vehicle_time_gps_synced_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_vehicle_time_rtc_valid_encode(double value)
{
    return (uint8_t)(value);
}

double network_vehicle_time_rtc_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool network_vehicle_time_rtc_valid_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_vehicle_time_rtc_valid_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

int network_gps_status_pack(
    uint8_t *dst_p,
    const struct network_gps_status_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->satellites, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->fix_valid, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->time_valid, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->position_valid, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->motion_valid, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->seq_counter, 0u, 0xffu);

    return (4);
}

int network_gps_status_unpack(
    struct network_gps_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->satellites = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fix_valid = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->time_valid = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->position_valid = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->motion_valid = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->seq_counter = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int network_gps_status_init(struct network_gps_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_gps_status_t));

    return 0;
}

uint8_t network_gps_status_satellites_encode(double value)
{
    return (uint8_t)(value);
}

double network_gps_status_satellites_decode(uint8_t value)
{
    return ((double)value);
}

bool network_gps_status_satellites_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool network_gps_status_satellites_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t network_gps_status_fix_valid_encode(double value)
{
    return (uint8_t)(value);
}

double network_gps_status_fix_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool network_gps_status_fix_valid_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_gps_status_fix_valid_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_gps_status_time_valid_encode(double value)
{
    return (uint8_t)(value);
}

double network_gps_status_time_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool network_gps_status_time_valid_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_gps_status_time_valid_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_gps_status_position_valid_encode(double value)
{
    return (uint8_t)(value);
}

double network_gps_status_position_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool network_gps_status_position_valid_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_gps_status_position_valid_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_gps_status_motion_valid_encode(double value)
{
    return (uint8_t)(value);
}

double network_gps_status_motion_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool network_gps_status_motion_valid_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool network_gps_status_motion_valid_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t network_gps_status_seq_counter_encode(double value)
{
    return (uint8_t)(value);
}

double network_gps_status_seq_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool network_gps_status_seq_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool network_gps_status_seq_counter_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int network_gps_position_pack(
    uint8_t *dst_p,
    const struct network_gps_position_t *src_p,
    size_t size)
{
    uint32_t latitude_deg;
    uint32_t longitude_deg;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    latitude_deg = (uint32_t)src_p->latitude_deg;
    dst_p[0] |= pack_left_shift_u32(latitude_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(latitude_deg, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(latitude_deg, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(latitude_deg, 24u, 0xffu);
    longitude_deg = (uint32_t)src_p->longitude_deg;
    dst_p[4] |= pack_left_shift_u32(longitude_deg, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(longitude_deg, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(longitude_deg, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(longitude_deg, 24u, 0xffu);

    return (8);
}

int network_gps_position_unpack(
    struct network_gps_position_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint32_t latitude_deg;
    uint32_t longitude_deg;

    if (size < 8u) {
        return (-EINVAL);
    }

    latitude_deg = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    latitude_deg |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    latitude_deg |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    latitude_deg |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->latitude_deg = (int32_t)latitude_deg;
    longitude_deg = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    longitude_deg |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    longitude_deg |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    longitude_deg |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);
    dst_p->longitude_deg = (int32_t)longitude_deg;

    return (0);
}

int network_gps_position_init(struct network_gps_position_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_gps_position_t));

    return 0;
}

int32_t network_gps_position_latitude_deg_encode(double value)
{
    return (int32_t)(value / 1e-07);
}

double network_gps_position_latitude_deg_decode(int32_t value)
{
    return ((double)value * 1e-07);
}

bool network_gps_position_latitude_deg_is_in_range(int32_t value)
{
    return ((value >= -900000000) && (value <= 900000000));
}

bool network_gps_position_latitude_deg_is_in_phys_range(double value)
{
    return ((value >= -90.0) && (value <= 90.0));
}

int32_t network_gps_position_longitude_deg_encode(double value)
{
    return (int32_t)(value / 1e-07);
}

double network_gps_position_longitude_deg_decode(int32_t value)
{
    return ((double)value * 1e-07);
}

bool network_gps_position_longitude_deg_is_in_range(int32_t value)
{
    return ((value >= -1800000000) && (value <= 1800000000));
}

bool network_gps_position_longitude_deg_is_in_phys_range(double value)
{
    return ((value >= -180.0) && (value <= 180.0));
}

int network_gps_motion_pack(
    uint8_t *dst_p,
    const struct network_gps_motion_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->gps_speed_kmh, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->gps_speed_kmh, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->heading_deg, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->heading_deg, 8u, 0xffu);

    return (4);
}

int network_gps_motion_unpack(
    struct network_gps_motion_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->gps_speed_kmh = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->gps_speed_kmh |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->heading_deg = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->heading_deg |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int network_gps_motion_init(struct network_gps_motion_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_gps_motion_t));

    return 0;
}

uint16_t network_gps_motion_gps_speed_kmh_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double network_gps_motion_gps_speed_kmh_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool network_gps_motion_gps_speed_kmh_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_gps_motion_gps_speed_kmh_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 655.35));
}

uint16_t network_gps_motion_heading_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double network_gps_motion_heading_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool network_gps_motion_heading_deg_is_in_range(uint16_t value)
{
    return (value <= 35999u);
}

bool network_gps_motion_heading_deg_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 359.99));
}

int network_motor_state_pack(
    uint8_t *dst_p,
    const struct network_motor_state_t *src_p,
    size_t size)
{
    uint16_t motor_speed_rpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    motor_speed_rpm = (uint16_t)src_p->motor_speed_rpm;
    dst_p[0] |= pack_left_shift_u16(motor_speed_rpm, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(motor_speed_rpm, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->sequencer_state, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->motor_status, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->motor_status, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->motor_status, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->motor_status, 24u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->seq_counter, 0u, 0xffu);

    return (8);
}

int network_motor_state_unpack(
    struct network_motor_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t motor_speed_rpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    motor_speed_rpm = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    motor_speed_rpm |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->motor_speed_rpm = (int16_t)motor_speed_rpm;
    dst_p->sequencer_state = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->motor_status = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->motor_status |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->motor_status |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->motor_status |= unpack_left_shift_u32(src_p[6], 24u, 0xffu);
    dst_p->seq_counter = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int network_motor_state_init(struct network_motor_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_motor_state_t));

    return 0;
}

int16_t network_motor_state_motor_speed_rpm_encode(double value)
{
    return (int16_t)(value);
}

double network_motor_state_motor_speed_rpm_decode(int16_t value)
{
    return ((double)value);
}

bool network_motor_state_motor_speed_rpm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_state_motor_speed_rpm_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

uint8_t network_motor_state_sequencer_state_encode(double value)
{
    return (uint8_t)(value);
}

double network_motor_state_sequencer_state_decode(uint8_t value)
{
    return ((double)value);
}

bool network_motor_state_sequencer_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool network_motor_state_sequencer_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint32_t network_motor_state_motor_status_encode(double value)
{
    return (uint32_t)(value);
}

double network_motor_state_motor_status_decode(uint32_t value)
{
    return ((double)value);
}

bool network_motor_state_motor_status_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool network_motor_state_motor_status_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967295.0));
}

uint8_t network_motor_state_seq_counter_encode(double value)
{
    return (uint8_t)(value);
}

double network_motor_state_seq_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool network_motor_state_seq_counter_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool network_motor_state_seq_counter_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int network_motor_current_pack(
    uint8_t *dst_p,
    const struct network_motor_current_t *src_p,
    size_t size)
{
    uint16_t id_a;
    uint16_t iq_a;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    iq_a = (uint16_t)src_p->iq_a;
    dst_p[0] |= pack_left_shift_u16(iq_a, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(iq_a, 8u, 0xffu);
    id_a = (uint16_t)src_p->id_a;
    dst_p[2] |= pack_left_shift_u16(id_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(id_a, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->motor_current_a, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->motor_current_a, 8u, 0xffu);

    return (6);
}

int network_motor_current_unpack(
    struct network_motor_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t id_a;
    uint16_t iq_a;

    if (size < 6u) {
        return (-EINVAL);
    }

    iq_a = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    iq_a |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->iq_a = (int16_t)iq_a;
    id_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    id_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->id_a = (int16_t)id_a;
    dst_p->motor_current_a = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->motor_current_a |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int network_motor_current_init(struct network_motor_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_motor_current_t));

    return 0;
}

int16_t network_motor_current_iq_a_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double network_motor_current_iq_a_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_current_iq_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_current_iq_a_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t network_motor_current_id_a_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double network_motor_current_id_a_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_current_id_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_current_id_a_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

uint16_t network_motor_current_motor_current_a_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double network_motor_current_motor_current_a_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_current_motor_current_a_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_current_motor_current_a_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 655.35));
}

int network_motor_voltage_pack(
    uint8_t *dst_p,
    const struct network_motor_voltage_t *src_p,
    size_t size)
{
    uint16_t vd_v;
    uint16_t vq_v;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->dc_bus_voltage_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->dc_bus_voltage_v, 8u, 0xffu);
    vq_v = (uint16_t)src_p->vq_v;
    dst_p[2] |= pack_left_shift_u16(vq_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(vq_v, 8u, 0xffu);
    vd_v = (uint16_t)src_p->vd_v;
    dst_p[4] |= pack_left_shift_u16(vd_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(vd_v, 8u, 0xffu);

    return (6);
}

int network_motor_voltage_unpack(
    struct network_motor_voltage_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t vd_v;
    uint16_t vq_v;

    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->dc_bus_voltage_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->dc_bus_voltage_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    vq_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    vq_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->vq_v = (int16_t)vq_v;
    vd_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    vd_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->vd_v = (int16_t)vd_v;

    return (0);
}

int network_motor_voltage_init(struct network_motor_voltage_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_motor_voltage_t));

    return 0;
}

uint16_t network_motor_voltage_dc_bus_voltage_v_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double network_motor_voltage_dc_bus_voltage_v_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_voltage_dc_bus_voltage_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_voltage_dc_bus_voltage_v_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 655.35));
}

int16_t network_motor_voltage_vq_v_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double network_motor_voltage_vq_v_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_voltage_vq_v_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_voltage_vq_v_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t network_motor_voltage_vd_v_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double network_motor_voltage_vd_v_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_voltage_vd_v_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_voltage_vd_v_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int network_motor_faults_pack(
    uint8_t *dst_p,
    const struct network_motor_faults_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->fault_flags, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->fault_flags, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->fault_flags, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->fault_flags, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->sw_faults, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->sw_faults, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->sw_faults, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->sw_faults, 24u, 0xffu);

    return (8);
}

int network_motor_faults_unpack(
    struct network_motor_faults_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fault_flags = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->fault_flags |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->fault_flags |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->fault_flags |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->sw_faults = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->sw_faults |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->sw_faults |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->sw_faults |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int network_motor_faults_init(struct network_motor_faults_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_motor_faults_t));

    return 0;
}

uint32_t network_motor_faults_fault_flags_encode(double value)
{
    return (uint32_t)(value);
}

double network_motor_faults_fault_flags_decode(uint32_t value)
{
    return ((double)value);
}

bool network_motor_faults_fault_flags_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool network_motor_faults_fault_flags_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967295.0));
}

uint32_t network_motor_faults_sw_faults_encode(double value)
{
    return (uint32_t)(value);
}

double network_motor_faults_sw_faults_decode(uint32_t value)
{
    return ((double)value);
}

bool network_motor_faults_sw_faults_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

bool network_motor_faults_sw_faults_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 4294967295.0));
}

int network_motor_estimator_pack(
    uint8_t *dst_p,
    const struct network_motor_estimator_t *src_p,
    size_t size)
{
    uint16_t flux_speed_rpm;
    uint16_t hall_speed_rpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->hall_angle_deg, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->hall_angle_deg, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->flux_angle_deg, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->flux_angle_deg, 8u, 0xffu);
    hall_speed_rpm = (uint16_t)src_p->hall_speed_rpm;
    dst_p[4] |= pack_left_shift_u16(hall_speed_rpm, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(hall_speed_rpm, 8u, 0xffu);
    flux_speed_rpm = (uint16_t)src_p->flux_speed_rpm;
    dst_p[6] |= pack_left_shift_u16(flux_speed_rpm, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(flux_speed_rpm, 8u, 0xffu);

    return (8);
}

int network_motor_estimator_unpack(
    struct network_motor_estimator_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t flux_speed_rpm;
    uint16_t hall_speed_rpm;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->hall_angle_deg = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->hall_angle_deg |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->flux_angle_deg = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->flux_angle_deg |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    hall_speed_rpm = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    hall_speed_rpm |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->hall_speed_rpm = (int16_t)hall_speed_rpm;
    flux_speed_rpm = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    flux_speed_rpm |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->flux_speed_rpm = (int16_t)flux_speed_rpm;

    return (0);
}

int network_motor_estimator_init(struct network_motor_estimator_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_motor_estimator_t));

    return 0;
}

uint16_t network_motor_estimator_hall_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double network_motor_estimator_hall_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_estimator_hall_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 35999u);
}

bool network_motor_estimator_hall_angle_deg_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 359.99));
}

uint16_t network_motor_estimator_flux_angle_deg_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double network_motor_estimator_flux_angle_deg_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_estimator_flux_angle_deg_is_in_range(uint16_t value)
{
    return (value <= 35999u);
}

bool network_motor_estimator_flux_angle_deg_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 359.99));
}

int16_t network_motor_estimator_hall_speed_rpm_encode(double value)
{
    return (int16_t)(value);
}

double network_motor_estimator_hall_speed_rpm_decode(int16_t value)
{
    return ((double)value);
}

bool network_motor_estimator_hall_speed_rpm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_estimator_hall_speed_rpm_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t network_motor_estimator_flux_speed_rpm_encode(double value)
{
    return (int16_t)(value);
}

double network_motor_estimator_flux_speed_rpm_decode(int16_t value)
{
    return ((double)value);
}

bool network_motor_estimator_flux_speed_rpm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_estimator_flux_speed_rpm_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int network_motor_phase_current_pack(
    uint8_t *dst_p,
    const struct network_motor_phase_current_t *src_p,
    size_t size)
{
    uint16_t phase_u_current_a;
    uint16_t phase_v_current_a;
    uint16_t phase_w_current_a;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    phase_u_current_a = (uint16_t)src_p->phase_u_current_a;
    dst_p[0] |= pack_left_shift_u16(phase_u_current_a, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(phase_u_current_a, 8u, 0xffu);
    phase_v_current_a = (uint16_t)src_p->phase_v_current_a;
    dst_p[2] |= pack_left_shift_u16(phase_v_current_a, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(phase_v_current_a, 8u, 0xffu);
    phase_w_current_a = (uint16_t)src_p->phase_w_current_a;
    dst_p[4] |= pack_left_shift_u16(phase_w_current_a, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(phase_w_current_a, 8u, 0xffu);

    return (6);
}

int network_motor_phase_current_unpack(
    struct network_motor_phase_current_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t phase_u_current_a;
    uint16_t phase_v_current_a;
    uint16_t phase_w_current_a;

    if (size < 6u) {
        return (-EINVAL);
    }

    phase_u_current_a = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    phase_u_current_a |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->phase_u_current_a = (int16_t)phase_u_current_a;
    phase_v_current_a = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    phase_v_current_a |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->phase_v_current_a = (int16_t)phase_v_current_a;
    phase_w_current_a = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    phase_w_current_a |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->phase_w_current_a = (int16_t)phase_w_current_a;

    return (0);
}

int network_motor_phase_current_init(struct network_motor_phase_current_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct network_motor_phase_current_t));

    return 0;
}

int16_t network_motor_phase_current_phase_u_current_a_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double network_motor_phase_current_phase_u_current_a_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_phase_current_phase_u_current_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_phase_current_phase_u_current_a_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t network_motor_phase_current_phase_v_current_a_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double network_motor_phase_current_phase_v_current_a_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_phase_current_phase_v_current_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_phase_current_phase_v_current_a_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}

int16_t network_motor_phase_current_phase_w_current_a_encode(double value)
{
    return (int16_t)(value / 0.01);
}

double network_motor_phase_current_phase_w_current_a_decode(int16_t value)
{
    return ((double)value * 0.01);
}

bool network_motor_phase_current_phase_w_current_a_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool network_motor_phase_current_phase_w_current_a_is_in_phys_range(double value)
{
    return ((value >= -327.68) && (value <= 327.67));
}
