#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "can_driver.h"

static const char *TAG = "can_example";

// Include the C header generated by cantools from your .dbc file
#include "network.h"

void can_rx_task(void *arg)
{
    twai_message_t rx_msg;
    
    ESP_LOGI(TAG, "CAN RX Task started. Listening for frames...");

    while (1) {
        // Block indefinitely until a frame is received
        if (can_driver_receive(&rx_msg, portMAX_DELAY) == ESP_OK) {
            
            // Switch on the ID, just like the old dispatch code, but much simpler
            switch (rx_msg.identifier) {
                case NETWORK_PEDAL_FRAME_ID: {
                    struct network_pedal_t decoded_pedal;
                    
                    // Use the cantools-generated unpack function!
                    network_pedal_unpack(&decoded_pedal, rx_msg.data, rx_msg.data_length_code);
                    
                    // You can now use decoded_pedal.throttle_raw directly in your app
                    ESP_LOGI(TAG, "Received Pedal Frame! Throttle: %d", decoded_pedal.throttle_raw);
                    break;
                }
                
                default:
                    // Unhandled message
                    break;
            }
        }
    }
}

void app_main(void)
{
    ESP_LOGI(TAG, "Starting DBC Example...");

    // 1. Initialize the driver (example uses 500kbps, GPIO 21 TX, GPIO 22 RX)
    // Adjust pins based on your hardware!
    CanInitFlags_t flags = { .loopback = 0, .listen_only = 0 };
    esp_err_t err = can_driver_init(GPIO_NUM_21, GPIO_NUM_22, 500000, flags);
    
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Failed to init CAN driver");
        return;
    }

    // 2. Start the RX processing task
    xTaskCreate(can_rx_task, "can_rx_task", 4096, NULL, 5, NULL);

    // 3. (Optional) Example of transmitting with timeout handling
    // This solves the old ESP_ERR_NO_MEM buffer issue!
    uint8_t dummy_payload[8] = {0};
    
    // Block for up to 50ms (pdMS_TO_TICKS(50)) waiting for space in the TX queue.
    if (can_driver_transmit(0x400, dummy_payload, 8, pdMS_TO_TICKS(50)) != ESP_OK) {
        ESP_LOGW(TAG, "TX Queue full, dropped frame after 50ms timeout");
    } else {
        ESP_LOGI(TAG, "Transmitted frame successfully");
    }

    // Task loops indefinitely
    while(1) {
        vTaskDelay(pdMS_TO_TICKS(1000));
    }
}
