#!/usr/bin/env python3
"""Validate the V5 DBC and prevent generated binding drift."""

from __future__ import annotations

import difflib
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import cantools


ROOT = Path(__file__).resolve().parents[1]
DBC_PATH = ROOT / "network.dbc"

EXPECTED_MESSAGES = {
    "PEDAL_STATUS": (0x110, 6, 20),
    "AUX_COMMAND": (0x210, 1, 100),
    "PACK_POWER": (0x310, 4, 100),
    "AUX_POWER": (0x311, 4, 100),
    "PACK_ENERGY": (0x312, 5, 5000),
    "VEHICLE_MOTION": (0x400, 8, 100),
    "VEHICLE_TIME": (0x401, 7, 1000),
    "GPS_STATUS": (0x410, 4, 1000),
    "GPS_POSITION": (0x411, 8, 200),
    "GPS_MOTION": (0x412, 4, 200),
    "MOTOR_STATE": (0x600, 8, 50),
    "MOTOR_CURRENT": (0x601, 6, 20),
    "MOTOR_VOLTAGE": (0x602, 6, 50),
    "MOTOR_FAULTS": (0x603, 8, 100),
    "MOTOR_ESTIMATOR": (0x604, 8, 20),
    "MOTOR_PHASE_CURRENT": (0x605, 6, None),
}


def normalize_generated_text(text: str) -> str:
    """Normalize line endings and cantools' nondeterministic timestamp."""
    normalized = text.replace("\r\n", "\n").replace("\r", "\n")
    timestamp_pattern = re.compile(
        r"(generated by cantools version \S+) .*?(\.)$"
    )
    lines = []
    for line in normalized.splitlines():
        line = timestamp_pattern.sub(r"\1 <generation-timestamp>\2", line)
        lines.append(line)
    return "\n".join(lines) + "\n"


def validate_database() -> None:
    database = cantools.database.load_file(
        str(DBC_PATH),
        database_format="dbc",
        strict=True,
    )

    if database.version != "ECT2026_CAN_V5":
        raise AssertionError(f"unexpected DBC version: {database.version!r}")

    if len(database.messages) != len(EXPECTED_MESSAGES):
        raise AssertionError(
            f"expected {len(EXPECTED_MESSAGES)} messages, "
            f"found {len(database.messages)}"
        )

    if {message.name for message in database.messages} != set(EXPECTED_MESSAGES):
        raise AssertionError("message names do not match the V5 contract")

    identifiers = [message.frame_id for message in database.messages]
    if len(set(identifiers)) != len(identifiers):
        raise AssertionError("message identifiers are not unique")

    for message in database.messages:
        expected_id, expected_length, expected_cycle = EXPECTED_MESSAGES[
            message.name
        ]

        if message.frame_id != expected_id:
            raise AssertionError(
                f"{message.name}: expected ID 0x{expected_id:X}, "
                f"found 0x{message.frame_id:X}"
            )
        if message.length != expected_length:
            raise AssertionError(
                f"{message.name}: expected length {expected_length}, "
                f"found {message.length}"
            )
        if message.cycle_time != expected_cycle:
            raise AssertionError(
                f"{message.name}: expected cycle {expected_cycle!r}, "
                f"found {message.cycle_time!r}"
            )
        if message.frame_id > 0x7FF:
            raise AssertionError(f"{message.name}: ID is not standard CAN")
        if getattr(message, "is_fd", False):
            raise AssertionError(f"{message.name}: CAN-FD is not allowed")
        if message.length > 8:
            raise AssertionError(
                f"{message.name}: classic-CAN payload exceeds eight bytes"
            )

        for signal in message.signals:
            if signal.byte_order != "little_endian":
                raise AssertionError(
                    f"{message.name}.{signal.name}: expected little-endian signal"
                )
            if signal.start + signal.length > message.length * 8:
                raise AssertionError(
                    f"{message.name}.{signal.name}: signal exceeds message length"
                )


def compare_generated_file(committed: Path, generated: Path) -> None:
    committed_text = normalize_generated_text(
        committed.read_text(encoding="utf-8")
    )
    generated_text = normalize_generated_text(
        generated.read_text(encoding="utf-8")
    )

    if committed_text == generated_text:
        return

    diff = difflib.unified_diff(
        committed_text.splitlines(),
        generated_text.splitlines(),
        fromfile=str(committed),
        tofile=str(generated),
        lineterm="",
    )
    raise AssertionError(
        "generated artifact drift detected:\n" + "\n".join(diff)
    )


def validate_generated_artifacts() -> None:
    with tempfile.TemporaryDirectory(prefix="can_driver_network_") as output:
        subprocess.run(
            [
                sys.executable,
                "-m",
                "cantools",
                "generate_c_source",
                str(DBC_PATH),
                "-o",
                output,
            ],
            check=True,
        )

        compare_generated_file(
            ROOT / "network.c",
            Path(output) / "network.c",
        )
        compare_generated_file(
            ROOT / "include" / "network.h",
            Path(output) / "network.h",
        )


def main() -> int:
    try:
        validate_database()
        validate_generated_artifacts()
    except (AssertionError, OSError, subprocess.CalledProcessError) as error:
        print(f"network artifact check failed: {error}", file=sys.stderr)
        return 1

    print("network.dbc and generated bindings are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
